name: shopify_ci
on:
  pull_request:
    branches:
    - master

env:
  SHOPIFY_STORE: mhoyle-store
  SHOPIFY_API_KEY: 34f5615db23c3e556f45532432dfaa3c
  SHOPIFY_API_SECRET: 0ad62e82f84d2c71daf9f98d5ff25e34
  THEMEKIT_TIMEOUT: 60s
  SHOPIFY_THEME_NAME: 'Experiment'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - uses: ./shopify-theme-api
      id: shopify-get
      with:
        action: 'get'

    - run: echo "${{ steps.shopify-get.outputs.themeId }} ${{ steps.shopify-get.outputs.themeExists }}"

    - run: echo "${{join(steps.shopify-get.outputs.*, '\n')}}"
